
// EN JS NECESITAMOS SABER COMO EN CUALQUIER LENGUAJE DONDE TERMINA LA INSTRUCCION QUE VA A INTERPRETAR
// PARA ELLO RECOMENDAMOS PONER ';' AL FINAL DE CADA INSTRUCCION
// TAMBIEN SE ENTIENDE QUE TERMINA LA INSTRUCCION CUANDO ENCUENTRA UN SALTO DE LINEA

// TIPADO DE DATOS:
// 1. STRING ==> CADENAS ALFANUMERICAS ==> SE ESCRIBEN ENTRECOMILLADOS
// 2. NUMBER ==> NUMEROS CON SU VALOR ARITMETICO CORRESPONDIENTE ==> SE ESCRIBEN SIN COMILLAS

// EL TIPADO DE DATOS EN JS ES AUTOMATICO ==> CUANDO LE ENTRA UN VALOR SE ASIGNA SU TIPO

// STRING --> CADENA DE CARACTERES OJO: NUMEROS SON CARACTERES AQUI, NO TIENEN VALOR
// LOS STRINGS SE ESCRIBEN SIEMPRE ENTRECOMILLADOS YA SEA SIMPLE O DOBLE
// DECLARACION DE MUTABLES (VARIABLE) ==> 'let'
// SE PUEDE DECLARAR SIN ASIGNAR ==> DEJANDOLA VACIA (='undefined')
let nombreSaludo;
let apellido1; let apellido2;
// SE PUEDEN DECLARA VARIAS A LA VEZ SEPARANDO CADA IDENTIFICADOR MEDIANTE UNA COMA ','
let dni, nif, calle, municipio, cp;
// CUANDO UNA VARIABLE NO TIENE ASIGNADO NINGUN VALOR ES 'undefined'
// ASIGNAMOS UN VALOR MEDIANTE EL OPERADOR DE ASIGNACION '='
// SI YA ESTA DECLARADA, NO USAMOS DE NUEVO EL COMANDO 'let'
nombreSaludo = "alumno ";
// PUEDO ASIGNAR VARIAS AL MISMO TIEMPO
apellido1= "Alvarez", apellido2= "Bermudez", dni= "01234567", nif= "01234567A", calle= "Avenida de Manoteras";

// DECLARACION DE INMUTABLES (CONSTANTE) ==> 'const'
// ES OBLIGATORIO ASIGNARLA EN SU DECLARACIÓN
// ASIGNAMOS UN VALOR MEDIANTE EL OPERADOR DE ASIGNACION '='
// NO ES NECESARIO PEGAR EL OPERADOR A NINGUNO DE LOS LADOS
// ESTE OPERADOR METE EL VALOR LO QUE TENGA A SU DERECHA EN EL ELEMENTO DE SU IZQUIERDA (SEGUN LO MIRAMOS)
const saludoIni = "          Hola ";
const saludoFin = "Coder!        ";

// NO PODEMOS VOLVER A ASIGNAR NINGUN VALOR A UNA CONSTANTE
// miSaludo = "Hello Coders!";

// OPERADOR PARA CONCATENAR CADENAS '+' UNE DOS CADENAS
// let nuevoSaludo = miSaludo + nombreSaludo

// ZONA DE PRUEBAS
// console.log(nombreSaludo);
nombreSaludo= "Sebas";
let miSaludo = saludoIni + "alumno " +  nombreSaludo + ". Tu eres mi " + saludoFin;
// console.log(nombreSaludo);
// console.log(miSaludo);

// UNA PROPIEDAD O METODO QUE DEVUELVE ALGO NO SE MUESTRA POR SI SOLO: DEBEMOS ENVIARLO A ALGUN LUGAR
// 1. PASARLO A LA CONSOLA
// console.log(miSaludo.length);
// 2. PASARLO (GUARDAR) EN OTRA VARIABLE PRA LUEGO TRABAJAR CON ELLA
// PROPIEDAD '.length' --> DEVUELVE/GUARDA LA LONGITUD DEL STRING
const longitudCadena = miSaludo.length;
// console.log(longitudCadena);
// METODO 'charAt(índice)' --> DEVUELVE/GUARDA EL CARACTER EN ESA POSICION
console.log(miSaludo.charAt(3));
// METODO 'charCodeAt(índice) --> DEVUELVE EL CODIGO UNICODE/ASCII DEL CARACTER SOLICITADO
console.log(miSaludo.charCodeAt(3));
// '.slice()' --> MUESTRA/GUARDA PARTE DE LA CADENA
console.log(miSaludo.slice(6,22));
// '.toUpperCase()' --> PASA TODO A MAYUSCULAS
console.log(miSaludo.toUpperCase());
// '.toLowerCase()' --> PASA TODO A MINUSCULAS
console.log(miSaludo.toLowerCase());

console.log(miSaludo.length);

// OPERATIVA DE GRABACION EN LA MISMA VARIABLE
miSaludo = miSaludo.trim();

// '.trim()' --> ELIMINA ESPACIOS AL INICIO Y AL FINAL DEL STRING
console.log(miSaludo);